### ISSUE TITLE
How can I use graphRNN code to generate graphs with costume attributes? 

### ISSUE THREAD

**Issue by thesaturdayafternoon** [JiaxuanYou/graph-generation#19]
Hello,
How can I use graphRNN code to generate graphs with costume node attributes?

**Comment by Nuyoah003** [comment]
I also encountered the same problem. I think the reason should be that only the adjacency matrix is considered in the dataset processing, so the node attributes are automatically ignored. How can the author solve this problem? thank you

**Comment by geopapa11** [comment]
I think I have created a solution for this. If many people are interested to have GraphRNN support node labels I can upload an extension version of GraphRNN in my github.
